meta_product_name: "Widz"
meta_title: "Widz - Un jardin sur votre balcon, facilement"
meta_description: "Widz, est l'application d'optimisation du jardinage sur balcons et terrasses. Plantes compatibles, alertes de soin des plantes, alertes météo, maintenir des plantes sur un balcon n'a jamais été aussi facile."
meta_image: "cover.png" # should exist in `app/assets/images/`

